import type { Field } from 'payload'

export const sectorsField: Field = {
  name: 'sector_interested',
  type: 'select',
  label: 'Sector Interested In',
  required: true,
  options: [
    { label: 'Sector Agnostic', value: 'sector_agnostic' },
    { label: 'Aerospace, Defence & Spacetech', value: 'aerospace_defence_spacetech' },
    { label: 'Agriculture & Foodtech', value: 'agriculture_foodtech' },
    { label: 'AI, ML & IoT', value: 'ai_ml_iot' },
    { label: 'Art, Culture & Architecture', value: 'art_culture_architecture' },
    { label: 'Automotive, EV & Smart Mobility', value: 'automotive_ev_smart_mobility' },
    { label: 'Blue Economy', value: 'blue_economy' },
    { label: 'Chemicals & Materials', value: 'chemicals_materials' },
    { label: 'Circular Economy', value: 'circular_economy' },
    { label: 'Climate Tech & Clean Energy', value: 'climate_tech_clean_energy' },
    { label: 'Data Mining & Analytics', value: 'data_mining_analytics' },
    { label: 'Edutech', value: 'edutech' },
    { label: 'Femtech', value: 'femtech' },
    { label: 'Fintech & Insurtech', value: 'fintech_insurtech' },
    { label: 'Healthcare & Life Sciences', value: 'healthcare_life_sciences' },
    { label: 'HR Tech & Smart Workforce', value: 'hr_tech_smart_workforce' },
    { label: 'Industry 4.0 & Advanced Manufacturing', value: 'industry_4_advanced_manufacturing' },
    { label: 'Lifestyle, Personal Care & D2C', value: 'lifestyle_personalcare_d2c' },
    { label: 'Marketing Tech & MICE', value: 'marketing_tech_mice' },
    { label: 'Media & Entertainment', value: 'media_entertainment' },
    { label: 'PropTech, Legal Tech & RegTech', value: 'proptech_legaltech_regtech' },
    { label: 'Retail Tech', value: 'retail_tech' },
    { label: 'SaaS, Software & IT/ITES', value: 'saas_software_it_ites' },
    { label: 'Smart Cities & E-Governance', value: 'smart_cities_e_governance' },
    {
      label: 'Social Impact, Rural Livelihood & Sustainability',
      value: 'social_impact_rural_livelihood_sustainability',
    },
    { label: 'Sports Tech & Gaming', value: 'sports_tech_gaming' },
    { label: 'Supply Chain & Logistics', value: 'supply_chain_logistics' },
    { label: 'Telecom, Networking & Hardware', value: 'telecom_networking_hardware' },
    { label: 'TextileTech & Fashion', value: 'textiletech_fashion' },
    { label: 'Travel & Tourism', value: 'travel_tourism' },
    { label: 'Web3.0, Blockchain, VR/AR', value: 'web3_blockchain_vr_ar' },
  ],

  admin: {
    description: 'From visitor_data.sectorInterested - sector user is interested in',
    readOnly: true,
  },
}
